// <auto-generated />
using System;
using BlazorShop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorShop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925193802_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorShop.Api.Model.CarItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CartShopId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartShopId");

                    b.HasIndex("ProductId");

                    b.ToTable("CarItems");
                });

            modelBuilder.Entity("BlazorShop.Api.Model.CartShop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CartShops");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("BlazorShop.Api.Model.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IconCss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IconCss = "fas fa-spa",
                            Name = "Beleza"
                        },
                        new
                        {
                            Id = 2L,
                            IconCss = "fas fa-couch",
                            Name = "Móveis"
                        },
                        new
                        {
                            Id = 3L,
                            IconCss = "fas fa-headphones",
                            Name = "Eletrônicos"
                        },
                        new
                        {
                            Id = 4L,
                            IconCss = "fas fa-shoe-prints",
                            Name = "Calçados"
                        });
                });

            modelBuilder.Entity("BlazorShop.Api.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 100,
                            CategoryId = 1L,
                            Description = "Um kit fornecido pela Natura, contendo produtos para cuidados com a pele",
                            ImageUrl = "/Imagens/Beleza/Beleza1.png",
                            Name = "Glossier - Beleza Kit",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 45,
                            CategoryId = 1L,
                            Description = "Um kit fornecido pela Curology, contendo produtos para cuidados com a pele",
                            ImageUrl = "/Imagens/Beleza/Beleza2.png",
                            Name = "Curology - Kit para Pele",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 30,
                            CategoryId = 1L,
                            Description = "Um kit fornecido pela Glossier, contendo produtos para cuidados com a pele",
                            ImageUrl = "/Imagens/Beleza/Beleza3.png",
                            Name = "Óleo de Coco Orgânico",
                            Price = 20m
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 60,
                            CategoryId = 1L,
                            Description = "Um kit fornecido pela Curology, contendo produtos para cuidados com a pele",
                            ImageUrl = "/Imagens/Beleza/Beleza4.png",
                            Name = "Schwarzkopf - Kit de cuidados com a pele e cabelo",
                            Price = 50m
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 85,
                            CategoryId = 1L,
                            Description = "Kit de cuidados com a pele, contendo produtos para cuidados com a pele e cabelos",
                            ImageUrl = "/Imagens/Beleza/Beleza5.png",
                            Name = "Kit de cuidados com a pele",
                            Price = 30m
                        },
                        new
                        {
                            Id = 6L,
                            Amount = 120,
                            CategoryId = 3L,
                            Description = "Air Pods - fones de ouvido sem fio intra-auriculares",
                            ImageUrl = "/Imagens/Eletronicos/eletronico1.png",
                            Name = "Fones de ouvidos",
                            Price = 100m
                        },
                        new
                        {
                            Id = 7L,
                            Amount = 200,
                            CategoryId = 3L,
                            Description = "Fones de ouvido dourados na orelha - esses fones de ouvido não são sem fio",
                            ImageUrl = "/Imagens/Eletronicos/eletronico2.png",
                            Name = "Fones de ouvido dourados",
                            Price = 40m
                        },
                        new
                        {
                            Id = 8L,
                            Amount = 300,
                            CategoryId = 3L,
                            Description = "Fones de ouvido pretos na orelha - esses fones de ouvido não são sem fio",
                            ImageUrl = "/Imagens/Eletronicos/eletronico3.png",
                            Name = "Fones de ouvido pretos",
                            Price = 40m
                        },
                        new
                        {
                            Id = 9L,
                            Amount = 20,
                            CategoryId = 3L,
                            Description = "Câmera Digital Sennheiser - Câmera digital de alta qualidade fornecida pela Sennheiser - inclui tripé",
                            ImageUrl = "/Imagens/Eletronicos/eletronico4.png",
                            Name = "Câmera digital Sennheiser com tripé",
                            Price = 600m
                        },
                        new
                        {
                            Id = 10L,
                            Amount = 15,
                            CategoryId = 3L,
                            Description = "Canon Digital Camera - Câmera digital de alta qualidade fornecida pela Canon",
                            ImageUrl = "/Imagens/Eletronicos/eletronico5.png",
                            Name = "Câmera Digital Canon",
                            Price = 500m
                        },
                        new
                        {
                            Id = 11L,
                            Amount = 60,
                            CategoryId = 3L,
                            Description = "Gameboy - Fornecido por Nintendo",
                            ImageUrl = "/Imagens/Eletronicos/tecnologia6.png",
                            Name = "Nintendo Gameboy",
                            Price = 100m
                        },
                        new
                        {
                            Id = 12L,
                            Amount = 212,
                            CategoryId = 2L,
                            Description = "Cadeira de escritório em couro preto muito confortável",
                            ImageUrl = "/Imagens/Moveis/moveis1.png",
                            Name = "Cadeira de escritório de couro preto",
                            Price = 50m
                        },
                        new
                        {
                            Id = 13L,
                            Amount = 112,
                            CategoryId = 2L,
                            Description = "Cadeira de escritório em couro rosa muito confortável",
                            ImageUrl = "/Imagens/Moveis/moveis2.png",
                            Name = "Cadeira de escritório de couro rosa",
                            Price = 50m
                        },
                        new
                        {
                            Id = 14L,
                            Amount = 90,
                            CategoryId = 2L,
                            Description = "Poltrona muito confortável",
                            ImageUrl = "/Imagens/Moveis/moveis3.png",
                            Name = "Espreguiçadeira",
                            Price = 70m
                        },
                        new
                        {
                            Id = 15L,
                            Amount = 95,
                            CategoryId = 2L,
                            Description = "Poltrona prateada muito confortável",
                            ImageUrl = "/Imagens/Moveis/moveis4.png",
                            Name = "Silver Lounge Chair",
                            Price = 120m
                        },
                        new
                        {
                            Id = 16L,
                            Amount = 100,
                            CategoryId = 2L,
                            Description = "Abajur de mesa de porcelana branco e azul",
                            ImageUrl = "/Imagens/Moveis/moveis6.png",
                            Name = "Luminária de mesa de porcelana",
                            Price = 15m
                        },
                        new
                        {
                            Id = 17L,
                            Amount = 73,
                            CategoryId = 2L,
                            Description = "Abajur de mesa de escritório",
                            ImageUrl = "/Imagens/Moveis/moveis7.png",
                            Name = "Office Table Lamp",
                            Price = 20m
                        },
                        new
                        {
                            Id = 18L,
                            Amount = 50,
                            CategoryId = 4L,
                            Description = "Tênis Puma confortáveis na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado1.png",
                            Name = "Tênis Puma",
                            Price = 100m
                        },
                        new
                        {
                            Id = 19L,
                            Amount = 60,
                            CategoryId = 4L,
                            Description = "Tênis coloridos - disponíveis na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado2.png",
                            Name = "Tênis Colodiros",
                            Price = 150m
                        },
                        new
                        {
                            Id = 20L,
                            Amount = 70,
                            CategoryId = 4L,
                            Description = "Tênis Nike azul - disponível na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado3.png",
                            Name = "Tênis Nike Azul",
                            Price = 200m
                        },
                        new
                        {
                            Id = 21L,
                            Amount = 120,
                            CategoryId = 4L,
                            Description = "Treinadores Hummel coloridos - disponíveis na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado4.png",
                            Name = "Tênis Hummel Coloridos",
                            Price = 120m
                        },
                        new
                        {
                            Id = 22L,
                            Amount = 100,
                            CategoryId = 4L,
                            Description = "Tênis Nike vermelho - disponível na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado5.png",
                            Name = "Tênis Nike Vermelho",
                            Price = 200m
                        },
                        new
                        {
                            Id = 23L,
                            Amount = 150,
                            CategoryId = 4L,
                            Description = "Sandálias Birkenstock - disponíveis na maioria dos tamanhos",
                            ImageUrl = "/Imagens/Calcados/calcado6.png",
                            Name = "Sandálidas Birkenstock",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("BlazorShop.Api.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            NameUser = "Caique"
                        },
                        new
                        {
                            Id = 2L,
                            NameUser = "Isabela"
                        });
                });

            modelBuilder.Entity("BlazorShop.Api.Model.CarItem", b =>
                {
                    b.HasOne("BlazorShop.Api.Model.CartShop", "CartShop")
                        .WithMany("CarItems")
                        .HasForeignKey("CartShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorShop.Api.Model.Product", "Product")
                        .WithMany("CarItems")
                        .HasForeignKey("ProductId");

                    b.Navigation("CartShop");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlazorShop.Api.Model.CartShop", b =>
                {
                    b.HasOne("BlazorShop.Api.Model.User", null)
                        .WithOne("CartShop")
                        .HasForeignKey("BlazorShop.Api.Model.CartShop", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorShop.Api.Model.Product", b =>
                {
                    b.HasOne("BlazorShop.Api.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlazorShop.Api.Model.CartShop", b =>
                {
                    b.Navigation("CarItems");
                });

            modelBuilder.Entity("BlazorShop.Api.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BlazorShop.Api.Model.Product", b =>
                {
                    b.Navigation("CarItems");
                });

            modelBuilder.Entity("BlazorShop.Api.Model.User", b =>
                {
                    b.Navigation("CartShop");
                });
#pragma warning restore 612, 618
        }
    }
}
